name: Build Triton
description: |
  Build Triton from a specified commit. This composite action will:
  - check if a GitHub artifact exists for this Triton commit, OS, and architecture: `triton-<short-hash>-<os>-<arch>`
  - if the artifact does not exist, check out Triton and build it, using the given LLVM installation directory; then,
    upload it as an artifact
  - if the artifact does exist, download and extract it
  - return the path the Triton installation directory as well as the build directory inside of it (e.g.,
    `build/cmake.linux-x86_64-cpython-3.14`).

  This action expects `sccache` to be set up by the caller.

inputs:
  triton_hash:
    description: Triton commit hash to build.
    required: true
  llvm_install_dir:
    description: The LLVM installation directory.
    required: true
outputs:
  triton_install_dir:
    description: The Triton installation directory.
    value: ${{ steps.setup.outputs.triton_install_dir }}
  triton_build_dir:
    description: The Triton build directory.
    value: ${{ steps.find.outputs.triton_build_dir }}

runs:
  using: composite
  steps:
    - name: Determine Triton installation directory
      id: setup
      shell: bash
      run: |
        TRITON_COMMIT_HASH="${{ inputs.triton_hash }}"
        echo "Using provided Triton hash: ${TRITON_COMMIT_HASH}"
        echo "triton_commit_hash=${TRITON_COMMIT_HASH}" >> ${GITHUB_ENV}

        SHORT_TRITON_COMMIT_HASH="${TRITON_COMMIT_HASH:0:8}"
        RUNNER_OS="$(echo "${{ runner.os }}" | tr '[:upper:]' '[:lower:]')"
        RUNNER_ARCH="$(echo "${{ runner.arch }}" | tr '[:upper:]' '[:lower:]')"
        INSTALL_DIR="triton-${SHORT_TRITON_COMMIT_HASH}-${RUNNER_OS}-${RUNNER_ARCH}"
        echo "Triton installation directory: ${INSTALL_DIR}"
        echo "triton_install_dir=${INSTALL_DIR}" >> ${GITHUB_ENV}
        echo "triton_install_dir=${INSTALL_DIR}" >> ${GITHUB_OUTPUT}

    - name: Check if artifact exists
      id: check-artifact
      uses: actions/github-script@v7
      with:
        script: |
          const artifacts = await github.rest.actions.listArtifactsForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
          });
          const artifact = artifacts.data.artifacts.find(a => a.name == `${process.env.triton_install_dir}`);
          if (artifact) {
            console.log(`Found existing Triton artifact: ${artifact.name}`);
            core.setOutput('exists', 'true');
            core.setOutput('artifact_id', artifact.id);
          } else {
            core.setOutput('exists', 'false');
          }

    - name: Checkout triton
      if: steps.check-artifact.outputs.exists == 'false'
      uses: actions/checkout@v4
      with:
        repository: triton-lang/triton
        ref: ${{ inputs.triton_hash }}
        path: ${{ steps.setup.outputs.triton_install_dir }}

    - name: Build Triton
      if: steps.check-artifact.outputs.exists == 'false'
      id: build
      working-directory: ${{ steps.setup.outputs.triton_install_dir }}
      shell: bash
      run: >
        TRITON_BUILD_WITH_CLANG_LLD=1
        CMAKE_C_COMPILER_LAUNCHER=sccache
        CMAKE_CXX_COMPILER_LAUNCHER=sccache
        LLVM_INCLUDE_DIRS=${{ inputs.llvm_install_dir }}/include
        LLVM_LIBRARY_DIR=${{ inputs.llvm_install_dir }}/lib
        LLVM_SYSPATH=${{ inputs.llvm_install_dir }}
        make dev-install

    - name: Dump Sccache Statistics
      if: steps.check-artifact.outputs.exists == 'false'
      shell: bash
      run: sccache --show-stats

    - name: Package Triton
      if: steps.check-artifact.outputs.exists == 'false'
      shell: bash
      run: |
        tar czf "${{ env.triton_install_dir }}.tar.gz" --exclude=.git "${{ env.triton_install_dir }}"

    - name: Upload Triton artifact
      if: steps.check-artifact.outputs.exists == 'false'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.triton_install_dir }}
        path: ${{ env.triton_install_dir }}.tar.gz

    - name: Download Triton artifact
      if: steps.check-artifact.outputs.exists == 'true'
      uses: actions/github-script@v7
      with:
        script: |
          const artifact_id = '${{ steps.check-artifact.outputs.artifact_id }}';
          console.log(`Downloading existing Triton artifact: ${artifact_id}`);
          const download = await github.rest.actions.downloadArtifact({
              owner: context.repo.owner,
              repo: context.repo.repo,
              artifact_id: artifact_id,
              archive_format: 'zip',
          });

          const fs = require('fs');
          const tempDir = require('os').tmpdir();
          const zipPath = require('path').join(tempDir, `${process.env.triton_install_dir}.zip`);
          console.log(`Downloading to: ${zipPath}`);
          fs.writeFileSync(zipPath, Buffer.from(download.data));

          const { execSync } = require('child_process');
          execSync(`unzip -q ${zipPath} -d ${tempDir}`);
          tarDir = require('path').join(tempDir, `${process.env.triton_install_dir}.tar.gz`);
          extractDir = process.cwd();
          console.log(`Extracting ${tarDir} to ${extractDir}`);
          execSync(`tar xzf ${tarDir} -C ${extractDir}`);

    - name: Find Triton build directory
      id: find
      shell: bash
      run: |
        TRITON_BUILD_DIR=$(find "${{ env.triton_install_dir }}" -type d -name "cmake.*" | head -1)
        if [ ! -d "$TRITON_BUILD_DIR" ]; then
          echo "Error: Triton build directory not found at $TRITON_BUILD_DIR"
          exit 1
        fi
        echo "triton_build_dir=${TRITON_BUILD_DIR}" >> $GITHUB_ENV
        echo "triton_build_dir=${TRITON_BUILD_DIR}" >> $GITHUB_OUTPUT
