name: Build Triton
description: |
  Build Triton from a specified commit. This composite action will:
  - check if a GitHub artifact exists for this Triton commit, OS, and architecture: `triton-<short-hash>-<os>-<arch>`
  - if the artifact does not exist, check out Triton and build it, using the given LLVM installation directory; then,
    upload it as an artifact
  - if the artifact does exist, download and extract it
  - return the path the Triton installation directory as well as the build directory inside of it (e.g.,
    `build/cmake.linux-x86_64-cpython-3.14`).

  This action expects `sccache` to be set up by the caller.

inputs:
  triton_hash:
    description: Triton commit hash to build.
    required: true
  llvm_install_dir:
    description: The LLVM installation directory.
    required: true
outputs:
  triton_install_dir:
    description: The Triton installation directory.
    value: ${{ steps.setup.outputs.triton_install_dir }}
  triton_build_dir:
    description: The Triton build directory.
    value: ${{ steps.find.outputs.triton_build_dir }}

runs:
  using: composite
  steps:
    - name: Determine Triton installation directory
      id: setup
      shell: bash
      run: |
        TRITON_COMMIT_HASH="${{ inputs.triton_hash }}"
        echo "Using provided Triton hash: ${TRITON_COMMIT_HASH}"
        echo "triton_commit_hash=${TRITON_COMMIT_HASH}" >> ${GITHUB_ENV}

        SHORT_TRITON_COMMIT_HASH="${TRITON_COMMIT_HASH:0:8}"
        SYSINFO=$(python ci/probe-sysinfo.py)
        INSTALL_DIR="triton-${SHORT_TRITON_COMMIT_HASH}-${SYSINFO}"
        echo "Triton installation directory: ${INSTALL_DIR}"
        echo "triton_install_dir=${INSTALL_DIR}" >> ${GITHUB_ENV}
        echo "triton_install_dir=${INSTALL_DIR}" >> ${GITHUB_OUTPUT}

    - name: Check if artifact exists
      id: check-artifact
      shell: bash
      env:
        VERBOSE: 1
      run: |
        echo "Using GITHUB_REPOSITORY=${GITHUB_REPOSITORY}"
        if python ci/fetch-artifact-id.py "${{ env.triton_install_dir }}"; then
          echo "Artifact ${{ env.triton_install_dir }} exists, skipping build."
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "Artifact ${{ env.triton_install_dir }} does not exist, will build Triton."
          echo "exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Checkout triton
      if: steps.check-artifact.outputs.exists == 'false'
      uses: actions/checkout@v4
      with:
        repository: triton-lang/triton
        ref: ${{ inputs.triton_hash }}
        path: ${{ steps.setup.outputs.triton_install_dir }}

    - name: Build Triton
      if: steps.check-artifact.outputs.exists == 'false'
      id: build
      working-directory: ${{ steps.setup.outputs.triton_install_dir }}
      shell: bash
      run: >
        TRITON_BUILD_WITH_CLANG_LLD=1
        CMAKE_C_COMPILER_LAUNCHER=sccache
        CMAKE_CXX_COMPILER_LAUNCHER=sccache
        LLVM_INCLUDE_DIRS=${{ inputs.llvm_install_dir }}/include
        LLVM_LIBRARY_DIR=${{ inputs.llvm_install_dir }}/lib
        LLVM_SYSPATH=${{ inputs.llvm_install_dir }}
        make dev-install

    - name: Dump Sccache Statistics
      if: steps.check-artifact.outputs.exists == 'false'
      shell: bash
      run: sccache --show-stats

    - name: Package Triton
      if: steps.check-artifact.outputs.exists == 'false'
      shell: bash
      run: |
        tar czf "${{ env.triton_install_dir }}.tar.gz" --exclude=.git "${{ env.triton_install_dir }}"

    - name: Upload Triton artifact
      if: steps.check-artifact.outputs.exists == 'false'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.triton_install_dir }}
        path: ${{ env.triton_install_dir }}.tar.gz
