// Empty stubs for the CPython C-API symbols libtriton.so imports (it is also a
// Python extension module). triton-ext-opt only runs MLIR passes, so these let
// libtriton load without a real libpython. Regenerate with gen-python-stubs.sh.

void PyBaseObject_Type(void) {}
void PyBool_Type(void) {}
void PyBuffer_IsContiguous(void) {}
void PyBuffer_Release(void) {}
void PyByteArray_AsString(void) {}
void PyByteArray_Size(void) {}
void PyByteArray_Type(void) {}
void PyBytes_AsString(void) {}
void PyBytes_AsStringAndSize(void) {}
void PyBytes_FromString(void) {}
void PyBytes_FromStringAndSize(void) {}
void PyBytes_Size(void) {}
void PyCFunction_Type(void) {}
void PyCMethod_New(void) {}
void PyCallable_Check(void) {}
void PyCapsule_GetContext(void) {}
void PyCapsule_GetName(void) {}
void PyCapsule_GetPointer(void) {}
void PyCapsule_New(void) {}
void PyCapsule_SetContext(void) {}
void PyCapsule_SetDestructor(void) {}
void PyCapsule_Type(void) {}
void PyDict_Contains(void) {}
void PyDict_GetItemString(void) {}
void PyDict_GetItemWithError(void) {}
void PyDict_New(void) {}
void PyDict_Next(void) {}
void PyDict_SetDefault(void) {}
void PyDict_Size(void) {}
void PyDict_Type(void) {}
void PyErr_Clear(void) {}
void PyErr_ExceptionMatches(void) {}
void PyErr_Fetch(void) {}
void PyErr_Format(void) {}
void PyErr_NormalizeException(void) {}
void PyErr_Occurred(void) {}
void PyErr_Restore(void) {}
void PyErr_SetObject(void) {}
void PyErr_SetString(void) {}
void PyErr_WarnEx(void) {}
void PyErr_WriteUnraisable(void) {}
void PyEval_AcquireThread(void) {}
void PyEval_GetBuiltins(void) {}
void PyEval_RestoreThread(void) {}
void PyEval_SaveThread(void) {}
void PyExc_BufferError(void) {}
void PyExc_FutureWarning(void) {}
void PyExc_ImportError(void) {}
void PyExc_IndexError(void) {}
void PyExc_MemoryError(void) {}
void PyExc_OverflowError(void) {}
void PyExc_RuntimeError(void) {}
void PyExc_StopIteration(void) {}
void PyExc_SystemError(void) {}
void PyExc_TypeError(void) {}
void PyExc_ValueError(void) {}
void PyException_SetCause(void) {}
void PyException_SetContext(void) {}
void PyException_SetTraceback(void) {}
void PyFloat_AsDouble(void) {}
void PyFloat_Type(void) {}
void PyFrame_GetBack(void) {}
void PyFrame_GetCode(void) {}
void PyFrame_GetLineNumber(void) {}
void PyFrozenSet_Type(void) {}
void PyGILState_Check(void) {}
void PyGILState_Ensure(void) {}
void PyGILState_GetThisThreadState(void) {}
void PyGILState_Release(void) {}
void PyGen_Type(void) {}
void PyImport_AddModule(void) {}
void PyImport_GetModuleDict(void) {}
void PyImport_ImportModule(void) {}
void PyIndex_Check(void) {}
void PyInstanceMethod_New(void) {}
void PyInstanceMethod_Type(void) {}
void PyInterpreterState_GetDict(void) {}
void PyIter_Check(void) {}
void PyIter_Next(void) {}
void PyList_Append(void) {}
void PyList_AsTuple(void) {}
void PyList_GetItem(void) {}
void PyList_New(void) {}
void PyList_SetSlice(void) {}
void PyList_Size(void) {}
void PyList_Type(void) {}
void PyLong_AsLong(void) {}
void PyLong_AsLongLongAndOverflow(void) {}
void PyLong_AsUnsignedLong(void) {}
void PyLong_AsUnsignedLongLong(void) {}
void PyLong_FromLong(void) {}
void PyLong_FromSize_t(void) {}
void PyLong_FromSsize_t(void) {}
void PyLong_Type(void) {}
void PyMem_Calloc(void) {}
void PyMem_Free(void) {}
void PyMethod_Type(void) {}
void PyModuleDef_Init(void) {}
void PyModule_AddFunctions(void) {}
void PyModule_AddObject(void) {}
void PyModule_GetFilenameObject(void) {}
void PyModule_GetName(void) {}
void PyModule_NewObject(void) {}
void PyModule_Type(void) {}
void PyNumber_Add(void) {}
void PyNumber_And(void) {}
void PyNumber_Check(void) {}
void PyNumber_Float(void) {}
void PyNumber_Invert(void) {}
void PyNumber_Long(void) {}
void PyNumber_Or(void) {}
void PyNumber_Xor(void) {}
void PyObject_CallFunctionObjArgs(void) {}
void PyObject_CallObject(void) {}
void PyObject_ClearWeakRefs(void) {}
void PyObject_Free(void) {}
void PyObject_GC_UnTrack(void) {}
void PyObject_GenericGetDict(void) {}
void PyObject_GenericSetDict(void) {}
void PyObject_GetAttr(void) {}
void PyObject_GetAttrString(void) {}
void PyObject_GetItem(void) {}
void PyObject_GetIter(void) {}
void PyObject_HasAttr(void) {}
void PyObject_HasAttrString(void) {}
void PyObject_Hash(void) {}
void PyObject_IsInstance(void) {}
void PyObject_IsTrue(void) {}
void PyObject_Malloc(void) {}
void PyObject_Repr(void) {}
void PyObject_RichCompareBool(void) {}
void PyObject_SetAttr(void) {}
void PyObject_SetAttrString(void) {}
void PyObject_SetItem(void) {}
void PyObject_Str(void) {}
void PyObject_Vectorcall(void) {}
void PyObject_VectorcallMethod(void) {}
void PyProperty_Type(void) {}
void PySequence_Check(void) {}
void PySequence_Fast(void) {}
void PySequence_GetItem(void) {}
void PySequence_List(void) {}
void PySequence_Size(void) {}
void PySequence_Tuple(void) {}
void PySet_Type(void) {}
void PyStaticMethod_New(void) {}
void PyStaticMethod_Type(void) {}
void PyThreadState_Clear(void) {}
void PyThreadState_DeleteCurrent(void) {}
void PyThreadState_New(void) {}
void PyThread_tss_create(void) {}
void PyThread_tss_delete(void) {}
void PyThread_tss_get(void) {}
void PyThread_tss_set(void) {}
void PyTuple_GetItem(void) {}
void PyTuple_New(void) {}
void PyTuple_Pack(void) {}
void PyTuple_SetItem(void) {}
void PyTuple_Size(void) {}
void PyTuple_Type(void) {}
void PyType_FromSpec(void) {}
void PyType_GetFlags(void) {}
void PyType_IsSubtype(void) {}
void PyType_Ready(void) {}
void PyType_Type(void) {}
void PyUnicode_AsEncodedString(void) {}
void PyUnicode_AsUTF8(void) {}
void PyUnicode_AsUTF8AndSize(void) {}
void PyUnicode_AsUTF8String(void) {}
void PyUnicode_Compare(void) {}
void PyUnicode_DecodeUTF8(void) {}
void PyUnicode_FromFormat(void) {}
void PyUnicode_FromString(void) {}
void PyUnicode_FromStringAndSize(void) {}
void PyUnicode_InternFromString(void) {}
void PyUnicode_Type(void) {}
void PyWeakref_NewRef(void) {}
void Py_GetVersion(void) {}
void _PyObject_GetDictPtr(void) {}
void _PyObject_New(void) {}
void _PyThreadState_UncheckedGet(void) {}
void _PyType_Lookup(void) {}
void _Py_Dealloc(void) {}
void _Py_FalseStruct(void) {}
void _Py_NoneStruct(void) {}
void _Py_NotImplementedStruct(void) {}
void _Py_TrueStruct(void) {}
