// This file contains stubs for Python C API functions that are required when
// loading the Triton library. These symbols are undefined unless Triton is
// loaded by Python; for testing extensions using Triton binaries (e.g.,
// `triton-opt`), we use these stubs to provide empty implementations and avoid
// link errors.

void PyBaseObject_Type() {}
void PyBool_Type() {}
void PyBuffer_IsContiguous() {}
void PyBuffer_Release() {}
void PyByteArray_AsString() {}
void PyByteArray_Size() {}
void PyByteArray_Type() {}
void PyBytes_AsString() {}
void PyBytes_AsStringAndSize() {}
void PyBytes_FromString() {}
void PyBytes_FromStringAndSize() {}
void PyBytes_Size() {}
void PyCallable_Check() {}
void PyCapsule_GetName() {}
void PyCapsule_GetPointer() {}
void PyCapsule_New() {}
void PyCapsule_Type() {}
void PyCFunction_Type() {}
void PyCMethod_New() {}
void _Py_Dealloc() {}
void PyDict_Contains() {}
void PyDict_Copy() {}
void PyDict_DelItemString() {}
void PyDict_GetItemString() {}
void PyDict_GetItemStringRef() {}
void PyDict_GetItemWithError() {}
void PyDict_New() {}
void PyDict_Next() {}
void PyDict_Size() {}
void PyDict_Type() {}
void PyErr_Clear() {}
void PyErr_ExceptionMatches() {}
void PyErr_Fetch() {}
void PyErr_Format() {}
void PyErr_NormalizeException() {}
void PyErr_Occurred() {}
void PyErr_Restore() {}
void PyErr_SetObject() {}
void PyErr_SetString() {}
void PyErr_WarnEx() {}
void PyEval_AcquireThread() {}
void PyEval_GetBuiltins() {}
void PyEval_RestoreThread() {}
void PyEval_SaveThread() {}
void PyExc_BufferError() {}
void PyException_SetCause() {}
void PyException_SetContext() {}
void PyException_SetTraceback() {}
void PyExc_FutureWarning() {}
void PyExc_ImportError() {}
void PyExc_IndexError() {}
void PyExc_MemoryError() {}
void PyExc_OverflowError() {}
void PyExc_RuntimeError() {}
void PyExc_StopIteration() {}
void PyExc_SystemError() {}
void PyExc_TypeError() {}
void PyExc_ValueError() {}
void _Py_FalseStruct() {}
void PyFloat_AsDouble() {}
void PyFloat_Type() {}
void PyFrame_GetBack() {}
void PyFrame_GetCode() {}
void PyFrame_GetLineNumber() {}
void PyFrozenSet_Type() {}
void PyGen_Type() {}
void Py_GetVersion() {}
void PyGILState_Check() {}
void PyGILState_Ensure() {}
void PyGILState_GetThisThreadState() {}
void PyGILState_Release() {}
void PyImport_AddModule() {}
void PyImport_GetModuleDict() {}
void PyImport_ImportModule() {}
void PyIndex_Check() {}
void PyInstanceMethod_New() {}
void PyInstanceMethod_Type() {}
void PyInterpreterState_Get() {}
void PyInterpreterState_GetDict() {}
void PyIter_Check() {}
void PyIter_Next() {}
void PyList_Append() {}
void PyList_AsTuple() {}
void PyList_GetItem() {}
void PyList_New() {}
void PyList_SetSlice() {}
void PyList_Size() {}
void PyList_Type() {}
void PyLong_AsLong() {}
void PyLong_AsLongLongAndOverflow() {}
void PyLong_AsunsignedLong() {}
void PyLong_AsunsignedLongLong() {}
void PyLong_FromLong() {}
void PyLong_FromSize_t() {}
void PyLong_FromSsize_t() {}
void PyLong_Type() {}
void PyMem_Calloc() {}
void PyMem_Free() {}
void PyMem_Malloc() {}
void PyMethod_Type() {}
void PyModule_AddFunctions() {}
void PyModule_AddObject() {}
void PyModuleDef_Init() {}
void PyModule_GetFilenameObject() {}
void PyModule_GetName() {}
void PyModule_NewObject() {}
void PyModule_Type() {}
void _Py_NoneStruct() {}
void _Py_NotImplementedStruct() {}
void PyNumber_Add() {}
void PyNumber_And() {}
void PyNumber_Check() {}
void PyNumber_Float() {}
void PyNumber_Invert() {}
void PyNumber_Long() {}
void PyNumber_Or() {}
void PyNumber_Xor() {}
void PyObject_CallFunctionObjArgs() {}
void PyObject_CallObject() {}
void PyObject_ClearManagedDict() {}
void PyObject_ClearWeakRefs() {}
void PyObject_GC_unTrack() {}
void PyObject_GenericGetDict() {}
void PyObject_GenericSetDict() {}
void PyObject_GetAttr() {}
void PyObject_GetAttrString() {}
void _PyObject_GetDictPtr() {}
void PyObject_GetItem() {}
void PyObject_GetIter() {}
void PyObject_HasAttr() {}
void PyObject_HasAttrString() {}
void PyObject_Hash() {}
void PyObject_IsInstance() {}
void PyObject_IsTrue() {}
void _PyObject_New() {}
void PyObject_Repr() {}
void PyObject_RichCompareBool() {}
void PyObject_SetAttr() {}
void PyObject_SetAttrString() {}
void PyObject_SetItem() {}
void PyObject_Str() {}
void PyObject_Vectorcall() {}
void PyObject_VectorcallMethod() {}
void PyObject_VisitManagedDict() {}
void PyProperty_Type() {}
void PySequence_Check() {}
void PySequence_Fast() {}
void PySequence_GetItem() {}
void PySequence_List() {}
void PySequence_Size() {}
void PySequence_Tuple() {}
void PySet_Type() {}
void PyStaticMethod_New() {}
void PyStaticMethod_Type() {}
void PyThreadState_Clear() {}
void PyThreadState_DeleteCurrent() {}
void PyThreadState_Get() {}
void PyThreadState_Getunchecked() {}
void PyThreadState_New() {}
void PyThread_tss_create() {}
void PyThread_tss_delete() {}
void PyThread_tss_get() {}
void PyThread_tss_set() {}
void _Py_TrueStruct() {}
void PyTuple_GetItem() {}
void PyTuple_New() {}
void PyTuple_Pack() {}
void PyTuple_SetItem() {}
void PyTuple_Size() {}
void PyTuple_Type() {}
void PyType_FromSpec() {}
void PyType_IsSubtype() {}
void _PyType_Lookup() {}
void PyType_Ready() {}
void PyType_Type() {}
void PyUnicode_AsEncodedString() {}
void PyUnicode_AsuTF8() {}
void PyUnicode_AsuTF8AndSize() {}
void PyUnicode_AsuTF8String() {}
void PyUnicode_DecodeuTF8() {}
void PyUnicode_FromFormat() {}
void PyUnicode_FromString() {}
void PyUnicode_FromStringAndSize() {}
void PyUnicode_InternFromString() {}
void PyUnicode_Type() {}
void PyWeakref_NewRef() {}
