#pragma once

#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/Dialect.h"
#include "triton/Dialect/TritonGPU/IR/Dialect.h"
#include "triton/Tools/LinearLayout.h"

// Generated by tablegen
#include "dialect/TritonAppleGPU/IR/Dialect.h.inc"
#define GET_ATTRDEF_CLASSES
#include "dialect/TritonAppleGPU/IR/TritonAppleGPUAttrDefs.h.inc"

#include "LinearLayoutDims.h"
