#ifndef TRITON_APPLEGPU_IR_DIALECT_H
#define TRITON_APPLEGPU_IR_DIALECT_H

#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/Dialect.h"
#include "triton/Dialect/TritonGPU/IR/Dialect.h"
#include "triton/Tools/LinearLayout.h"

// Generated by tablegen
#include "Dialect/TritonAppleGPU/IR/Dialect.h.inc"
#define GET_ATTRDEF_CLASSES
#include "Dialect/TritonAppleGPU/IR/TritonAppleGPUAttrDefs.h.inc"

#include "LinearLayoutDims.h"

#endif // TRITON_APPLEGPU_IR_DIALECT_H
