name: CI
# A continuous integration workflow for triton-ext.

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  pre-commit:
    name: Run pre-commit hooks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: python -m pip install -r requirements.txt
      - name: Check pre-commit
        run: python -m pre_commit run --all-files --verbose
      - name: Print diff of changes if pre-commit failed
        if: failure()
        run: git diff

  build:
    name: Build on ${{ matrix.config.runner }}
    runs-on: ${{ matrix.config.runs_on }}
    timeout-minutes: 300
    defaults: {run: {shell: bash}}
    env:
      VERBOSE: 1

    strategy:
      fail-fast: true
      matrix:
        config:
        - {runner: 'Ubuntu 22.04', runs_on: 'ubuntu-22.04', target-os: 'ubuntu', arch: 'x64'}
        # Eventually, this matrix can be expanded to include more platforms (see
        # `triton/.github/workflows/llvm-build.yml`):

    steps:
      - name: Checkout triton-ext
        uses: actions/checkout@v6.0.2

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Setup virtual environment
        run: |
          python -m venv "$HOME/.venv"
          echo "$HOME/.venv/bin" >> $GITHUB_PATH

      - name: Install dependencies
        # These dependencies are installed in a separate step so that we can use
        # the updated `$GITHUB_PATH`.
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          echo "pip version: $(pip --version)"
          echo "pip location: $(which pip)"
          echo "python version: $(python --version)"
          echo "python location: $(which python)"

      - name: Document commit hashes
        id: hashes
        # See `update-triton.yml` for where this commit hash is updated.
        run: |
          TRITON_HASH=$(cat ci/triton-hash.txt)
          echo "Triton hash: $TRITON_HASH"

          LLVM_HASH=$(python ci/fetch_llvm_hash.py $TRITON_HASH)
          echo "LLVM hash: $LLVM_HASH"

      - name: Download LLVM artifact
        run:
          python ci/download_llvm.py

      - name: Download and install Triton wheel
        run: |
          WHEEL=$(python ci/download_triton_wheel.py nightly)
          pip install $WHEEL

      - name: Build Triton extensions
        run: make build

      - name: Install Triton extensions
        run: make install

      - name: Run tests
        run: make test

      - name: List files
        run: du -d 3 -h .
